language: android
jdk: oraclejdk8
os: 
  - linux

env:
  global:
    - ANDROID_API = 24
    - EMULATOR_API = 21
    - ANDROID_API_BUILD_TOOLS = 25.0.0

android:
  components: 
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    # - addon-google_apis-google-19 # google play services
    #- sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
    #- sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

# Android BUILD TOOLS 25.0 이상 사용시 적용
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

# Run Android Emulator...
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &