/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wnsud_ndk_practice_MainActivity */

#ifndef _Included_com_example_wnsud_ndk_practice_MainActivity
#define _Included_com_example_wnsud_ndk_practice_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wnsud_ndk_practice_MainActivity
 * Method:    convertNativeGray
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_wnsud_ndk_1practice_MainActivity_convertNativeGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
