/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class duribon_dlug_org_duribonduribon_Activities_MainActivity */

#ifndef _Included_duribon_dlug_org_duribonduribon_Activities_MainActivity
#define _Included_duribon_dlug_org_duribonduribon_Activities_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
